#:import color kivy.utils.get_color_from_hex
<AppBar>:
    size_hint_y:None
    height:"60dp"
    canvas.before:
        Color:
            rgba:color("#181f2b")
        Rectangle:
            pos:self.pos
            size:self.size
            
    IconButton:
        icon:"menu"
        pos_hint:{"center_x":.08,"center_y":.5}
        on_release:
            print("ok")   
    
            
    Label:
        text:"Demo App"
        pos_hint:{"center_x":.25,"center_y":.5}